const List<Map<String, dynamic>> allergicList = [
  {"id": 1, "name": "Drug Allergy"},
  {"id": 2, "name": "Food Allergy"},
  {"id": 3, "name": "Insect Allergy"},
  {"id": 4, "name": "Latex Allergy"},
  {"id": 5, "name": "Mold Allergy"},
  {"id": 6, "name": "Pet Allergy"},
  {"id": 7, "name": "Pollen Allergy"},
  {"id": 8, "name": "Other"},
  {"id": 9, "name": "None"},
];

const List<Map<String, dynamic>> genderList = [
  {"id": 1, "name": "Male"},
  {"id": 2, "name": "Female"},
  {"id": 3, "name": "Other"}
];

const List<Map<String, dynamic>> districtList = [
  {"id": 1, "name": "Ambala"},
  {"id": 2, "name": "Bhiwani"},
  {"id": 3, "name": "Charkhi Dadri"},
  {"id": 4, "name": "Faridabad"},
  {"id": 5, "name": "Fatehabad"},
  {"id": 6, "name": "Gurugram (Gurgaon)"},
  {"id": 7, "name": "Hisar"},

];
const List<Map<String, dynamic>> familytypeList = [
  {"id": 1, "name": "Modern"},
  {"id": 2, "name": "Moderate"},
  {"id": 3, "name": "Orthodox"}
];
const List<Map<String, dynamic>> fatherOccupationList = [
{"id": 1, "name": "Accountant"},
{"id": 2,"name":"Architect"},
{"id": 3,"name":"Engineer"},
{"id": 4,"name": "Medical Practitioner"},
{"id": 5,"name":"Nurse"},
{"id": 6,"name":"Business Owner/Entrepreneur"},
{"id": 7,"name":"Executive"},
{"id": 8,"name":"Software Professional"},
{"id": 9,"name":"Manager"},
{"id": 10,"name":"Supervisor"},
{"id": 11,"name":"Officer"},
{"id": 12,"name":"Engineer-Non IT"},
{"id": 13,"name":"Technician"},
{"id": 14,"name":"Clerk"},
{"id": 15,"name":"Marketing Professional"},
{"id": 16,"name":"Administration Manager"},
{"id": 17,"name":"Administration Supervisor"},
{"id": 18,"name":"Administration Officer"},
{"id": 19,"name":"Agriculture & Farming Professional"},
{"id": 20,"name":"Horticulturist"},
{"id": 21,"name":"Pilot"},
{"id": 22,"name":"Air Hostess/Flight Attendant"},
{"id": 23,"name":"Airline Professional"},
{"id": 24,"name":"Interior Designer"},
{"id": 25,"name":"Chartered Accountant"},
{"id": 26,"name":"Company Secretary"},
{"id": 27,"name":"Accounts/Finance Professional"},
{"id": 28,"name":"Banking Professional"},
{"id": 29,"name":"Auditor"},
{"id": 30,"name":"Financial Accountant"},
{"id": 31,"name":"Financial Analyst/Planning"},
{"id": 32,"name":"Investment Professional"},
{"id": 33,"name":"Fashion Designer"},
{"id": 34,"name":"Beautician"},
{"id": 35,"name":"Hairstylist"},
{"id": 36,"name":"Jewelry Designer"},
{"id": 37,"name":"Designer(others)"},
{"id": 38,"name":"Makeup Artist"},
{"id": 39,"name":"BPO/KPO/ITES Professional"},
{"id": 40,"name":"Customer Service Professional"},
{"id": 41,"name":"Civil Services(IAS/IPS/IRS/IES/IFS)"},
{"id": 42,"name":"Consultant"},
{"id": 43,"name":"Corporate Communication"},
{"id": 44,"name":"Corporate Planning"},
{"id": 45,"name":"Operations Management"},
{"id": 46,"name":"Sales Professional"},
{"id": 47,"name":"Senior Manager/Manager"},
{"id": 48,"name":"Subject Matter Expert"},
{"id": 49,"name":"Business Development Professional"},
{"id": 50,"name":"Content Writer"},
{"id": 51,"name":"Army"},
{"id": 52,"name":"Navy"},
{"id": 53,"name":"Paramilitary"},
{"id": 54,"name":"Doctor"},
{"id": 55,"name":"Dentist"},
{"id": 56,"name":"Surgeon"},
{"id": 57,"name":"Veterinary Doctor"},
{"id": 58,"name":"Professor/Lecturer"},
{"id": 59,"name":"Teaching/Academician"},
{"id": 60,"name":"Education Professional"},
{"id": 61,"name":"Training Professional"},
{"id": 62,"name":"Research Assistant"},
{"id": 63,"name":"Research Scholar"},
{"id": 64,"name":"Product Manager-Non IT"},
{"id": 65,"name":"Quality Assurance Engineer-Non IT"},
{"id": 66,"name":"Hotel/Hospitality Profession"},
{"id": 67,"name":"Restaurant/Catering Professional"},
{"id": 68,"name":"Chef/Cook"},
{"id": 69,"name":"Software Professional"},
{"id": 70,"name":"Hardware Professional"},
{"id": 71,"name":"Product Manager"},
{"id": 72,"name":"Program Manager"},
{"id": 73,"name":"Animator"},
{"id": 74,"name":"Cyber/Network Security"},
{"id": 75,"name":"UI/UX Designer"},
{"id": 76,"name":"Web/Graphics Designer"},
{"id": 77,"name":"Software Consultant"},
{"id": 78,"name":"Data Analyst"},
{"id": 79,"name":"Data Scientist"},
{"id": 80,"name":"Network Engineer"},
{"id": 81,"name":"Quality Assurance Engineer"},
{"id": 82,"name":"Lawyer & Legal Professional"},
{"id": 83,"name":"Legal Assistant"},
{"id": 84,"name":"Journalist"},
{"id": 85,"name":"Media Professional"},
{"id": 86,"name":"Entertainment Professional"},
{"id": 87,"name":"Event Management Professional"},
{"id": 88,"name":"Advertising/PR Professional"},
{"id": 89,"name":"Actor/Model"},
{"id": 90,"name":"Artist"},
{"id": 91,"name":"Healthcare Professional"},
{"id": 92,"name":"Paramedical Professional"},
{"id": 93,"name":"Pharmacist"},
{"id": 94,"name":"Physiotherapist"},
{"id": 95,"name":"Psychologist"},
{"id": 96,"name":"Therapist"},
{"id": 97,"name":"Dietician/Nutritionist"},
{"id": 98,"name":"Lab Technician"},
{"id": 99,"name":"Medical Represetative"},
{"id": 100,"name":"Mariner/Merchant Navy"},
{"id": 101,"name":"Sailor"},
{"id": 102,"name":"Librarian"},
{"id": 103,"name":"Agent/Broker/Trader"},
{"id": 104,"name":"Fitness Professional"},
{"id": 105,"name":"Security Professional"},
{"id": 106,"name":"Social Worker/Volunteer/NGO"},
{"id": 107,"name":"Sportsperson"},
{"id": 108,"name":"Travel Professional"},
{"id": 109,"name":"Singer"},
{"id": 110,"name":"Writer"},
{"id": 111,"name":"Politician"},
{"id": 112,"name":"Police"},
{"id": 113,"name":"Law Enforcement Officer"},
{"id": 114,"name":"Scientist/Researcher"},
{"id": 115,"name":"Government Employee"},
{"id": 116,"name":"Business"},
{"id": 117,"name":"Others"},
];

const List<Map<String, dynamic>> appearanceList = [
  {"id": 1, "name": "Beard"},
  {"id": 2, "name": "Non-Beard"}
];

const List<Map<String, dynamic>> manglikList = [
  {"id": 1, "name": "Manglik"},
  {"id": 2, "name": "Non Manglik"},
];
const List<Map<String, dynamic>> motherOccupationList = [
  {"id": 1, "name": "House Wife"},
  {"id": 2, "name": "Working"},
];
const List<Map<String, dynamic>> skinToneList = [
  {"id": 1, "name": "Fair"},
  {"id": 2, "name": "Whitish"},
  {"id": 3, "name": "Dusky"},
  {"id": 4, "name": "Dark"},
];

const List<Map<String, dynamic>> dietList = [
  {"id": 1, "name": "Vegetarian"},
  {"id": 2, "name": "Non-Vegetarian"},
  {"id": 3, "name": "Ocassionally Non-Vegetarian"},
  {"id": 4, "name": "Eggetarian"}
];
